## Lesson 04 — Taking Input, Reading and Writing Files, Functions

This class goes over some principles of interacting with your python scripts - through input, script parameters, files, etc. We will also cover a bit more in-depth how to write functions in a more flexible way.

### Readings

* Shaw: Exercises 11-26
* [Data Loading, Storage, and File Formats, Wes McKinney](https://wesmckinney.com/book/accessing-data)

### Table of Contents

* [Taking Input](#Taking-Input)
* [Reading Files](#Reading-Files)
* [Writing Files](#Writing-Files)
* [Functions](#Functions)

### Taking Input

In Shaw's _Learn Python The Hard Way_, he uses `input()` and `argv` to take input from the user. 

These **don't work very well with Jupyter notebooks**, but we will cover them because they can be useful in Python scripts.

#### variables

The most basic way of taking input is though script variables. They are hardcoded during the run of your script, and do not change during the execution of your code.

In [1]:
a = 1
a

1

#### `input()`

The input() function halts the program and prompts the user for a variable, that gets stored into the variable. It's important to note that **the output will always be a string**.

The following example won't work in a Jupyter notebook, so you will have to run it as a Python script. You can create a local script with the ending `.py` with the following content:

```python
x = input("What is the value for x? ")  # <- won't work on a notebook
print(x)
```

You are then able to run it with:

```bash
python example.py
```

#### `argv`

When you import the `argv` special variable, it allows you to pass strings, numbers, and filenames to your Python code. 

It also doesn't work in Jupyter notebooks, so you'll have to use a workaround. You can create a local script with the ending `.py` with the following content:

```python
from sys import argv

script = argv[0]
value1 = argv[1]

print(f"script: {script}")
print(f"first: {value1}")
```

You are then able to run it with:

```
python example.py foo bar
```

- `argv[0]`: is the first argument of the program, in this case it is `example.py`
- `argv[1]`: is the second argument of the program, in this case it is `foo`

This piece of code does not check if the correct number of arguments is provided: `bar` is ignored, and if you provide less arguments than it needs, it will raise an error (just try it!).

Adding code to the beginning of your code would check if the correct number of arguments is entered and exit if not:

```python
from sys import argv
from sys import exit

if len(argv) != 2:
    print(f"Usage: python {argv[0]} value1")
    exit(1)

script = argv[0]
value1 = argv[1]

print(f"script: {script}")
print(f"first: {value1}")
```

You may now call your script using the following pattern:

```bash
python example.py foobar
```

If you pass a different number of arguments, the script will exit early.

#### Environmental variables


An environmental variable is a variable defined outside the Python script, in the **operating system**. They are always read as **string**, and can be read using `os.environ`.

We will not cover environmental variables in this course: they are often used on the deployment of remote applications.

We can export an environment variable using a Terminal the `export` function under Linux or MacOs:

```bash
export VARIABLE=foobar
```

Then read this on Python:

```python
import os

variable = os.environ.get("VARIABLE")
print(variable)
```

#### `ipywidgets`

Notebooks have their own way of providing dynamic input to you through [`ipywidgets`](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Basics.html). Widgets are eventful python objects that have a representation in the browser, often as a control like a slider, textbox, etc.

The documentation of the library is very extensive, so we will cover only common examples:

In [2]:
# install and import the library
%pip install ipywidgets
from ipywidgets import interact

Requirement already satisfied: ipywidgets in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipywidgets) (9.11.0)
Requirement already satisfied: traitlets>=4.3.1 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: decorator>=5.1.0 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: pexpect>4.6 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

You are able to use the function `interact()` to require input that can be used within the cell in a function. Below, there are three examples of this input: as a **slider** for a number, as a **text box** for arbitrary strings and as a **dropdown** for different choices.

In [3]:
def f(x):
    print(f"The chosen number is {x}")


interact(f, x=5)

interactive(children=(IntSlider(value=5, description='x', max=15, min=-5), Output()), _dom_classes=('widget-in…

In [4]:
def f(word):
    print(f"The {word} is the word")


interact(f, word="Bird")

interactive(children=(Text(value='Bird', description='word'), Output()), _dom_classes=('widget-interact',))

In [5]:
def f(fruit):
    print(f"I have chosen {fruit}")


interact(f, fruit=["apples", "oranges"]);

interactive(children=(Dropdown(description='fruit', options=('apples', 'oranges'), value='apples'), Output()),…

#### Beginning your notebook or script

A typical script or IPython notebook might begin like this:

In [6]:
# you might need to install pandas, if you haven't already
%pip install pandas numpy

Requirement already satisfied: pandas in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
# import required packages
import pandas as pd
import numpy as np
import pathlib

In [8]:
# define file paths and variables
path_input_file = pathlib.Path("./input.txt")
path_output_file = pathlib.Path("./output.txt")
iterations = 10
evalue = 1e-5
color = "dark blue"
title = "My plot"

#### Documenting your steps

We often document what is going in the cell (what we plan to do) using markdown comments before, and when required individual code comments.

The purpose of those is to make your script more easily readable. Remember that **programmers spend more time reading than writing code**.

For documentation we can use basic markdown syntax:

## Headers

- Bullet points
- [ ] Task list
1. Numbered
2. Items

Your text can also be **bold**, _italic_ or ~~strikethrough~~. You can also provide [links](https://www.markdownguide.org/cheat-sheet/) or tables:

| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        | 

You can also separate parts either in different cells or using rulers, like below:

---

You may also quote things:

> "Any fool can write code that a computer can understand. Good programmers write code that humans can understand." ― Martin Fowler

Or display images (from external sources or from the disk):

![python](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/200px-Python-logo-notext.svg.png)

You can also display comments in the code using `#`. Developers prefer proper documentation, but comments are also an option to provide quick explanation for some design decisions.

For notebook, we want to take advantage of the notebook style: use **one cell per logical step** and make sure the script always runs from **top to bottom**.

In [9]:
# here is my super complicated code cell comment
print("Hello world")

Hello world

### Reading Files

We can read in a text file using `open()` and then print or use it all at once or one line at a time. 

**Note**: when we read the lines of a file, the lines are removed from the file handle object (called a `TextIOWrapper`).

A filename is simply a string providing the relative or full path to a file:

In [10]:
filename = "../data/woodchuck.txt"

Often, we prefer to use [pathlib](https://docs.python.org/3/library/pathlib.html) instead. This is because it offers us many utilities for interacting with files that strings do not have.

In [11]:
filename = pathlib.Path("../data/woodchuck.txt")

One of these utilities is the `exists()` method, to ensure a file exists and your file can be loaded correctly:

In [12]:
filename.exists()

True

#### Read all at once

Notice that we need to close the file after we are done with it. If you open a file, you will need to close it, because your system expects it to write buffered data to disk. The recommendation here is to use a `with` statement (see below).

In [13]:
txt = open(filename)

print(f"Content of file {filename}:")
print()
content = txt.read()
print(content)

txt.close()  # do not forget to close the file

Content of file ../data/woodchuck.txt:

How much wood
Would a woodchuck chuck
If a woodchuck could chuck wood?

When printing the content, the newlines will be rendered. When checking the value of the variable, it will display the newline characters:

In [14]:
content

'How much wood\nWould a woodchuck chuck\nIf a woodchuck could chuck wood?\n'

In [15]:
type(txt)

_io.TextIOWrapper

#### Read one line at a time

Reading one line at a time with the `readline()` method ensures your reader iterates over the file, advancing each time until the next `\n` character, and returning you the result. Once the iterator has finished, `''` will be returned.

This is useful if you do not need a lot of data (just a couple of rows), or want to save memory during processing. This function is commonly used with a `while` loop.

In [16]:
txt = open(filename)

txt.readline()

'How much wood\n'

In [17]:
txt.readline()

'Would a woodchuck chuck\n'

In [18]:
txt.readline()

'If a woodchuck could chuck wood?\n'

In [19]:
txt.readline()

''

In [20]:
txt.close()

#### Read lines as a list

For general usability, the best way to read text files is using `readlines()`. It will automatically load and split all lines into a list that can be used together with a `for` loop:

In [21]:
txt = open(filename)

lines = txt.readlines()
txt.close()

lines

['How much wood\n',
 'Would a woodchuck chuck\n',
 'If a woodchuck could chuck wood?\n']

In [22]:
for line in lines:
    print(line.strip())

How much wood
Would a woodchuck chuck
If a woodchuck could chuck wood?

#### Open in a `with` block. Then use `for` loop, `read()`, `readline()`, or `readlines()`.

This is the preferred method of working with files. A `with` statement (also called a [context manager](https://realpython.com/python-with-statement/)) makes sure that the object is closed, even if part of application logic fails. 

By the end of the `with` statement, the file close will automatically be called for you, ensuring the object gets properly closed and resources released.

In [23]:
with open(filename) as f:
    for line in f:
        line = line.rstrip()
        print(line)

How much wood
Would a woodchuck chuck
If a woodchuck could chuck wood?

In [24]:
with open(filename) as f:
    lines = f.read()
lines

'How much wood\nWould a woodchuck chuck\nIf a woodchuck could chuck wood?\n'

In [25]:
with open(filename) as f:
    line = f.readline().strip()
line

'How much wood'

In [26]:
with open(filename) as f:
    lines = f.readlines()
lines

['How much wood\n',
 'Would a woodchuck chuck\n',
 'If a woodchuck could chuck wood?\n']

In [27]:
with open(filename) as f:
    lines = [line.rstrip() for line in f.readlines()]
lines

['How much wood',
 'Would a woodchuck chuck',
 'If a woodchuck could chuck wood?']

#### Pandas can also read files, but it's better with tables.

`pandas` is able to read files as if they were a CSV. This option only useful if your data is in the common text files formats (e.g. CSV, TSV or event XLSX).

In [28]:
df = pd.read_csv(filename, header=None)

In [29]:
df

                                  0
0                     How much wood
1           Would a woodchuck chuck
2  If a woodchuck could chuck wood?

#### pathlib

As previously said, `pathlib` offers us some shortcuts for easily working with files. If all we want is to quickly read a file, we can do it using `read_text()`:

In [30]:
filename

PosixPath('../data/woodchuck.txt')

In [31]:
print(filename.read_text())

How much wood
Would a woodchuck chuck
If a woodchuck could chuck wood?

### Writing Files

We can write files using `write()`. This follows the same patterns as reading, but the file `mode` has to be changed. **Multiple modes can be used at once**.

The following write modes are available:

| Mode | Explanation                                                                                         |
|------|-----------------------------------------------------------------------------------------------------|
|  `w` | Write-only. Overwrites a file if it exists, otherwise creates it. (usual mode)                      |
|  `a` | Append-only. Appends the output to the end of the existing file if it exists, otherwise creates it. |
|  `b` | Binary mode (writes bytes rather than text)                                                         |
|  `+` | Open a disk file for updating (reading and writing).                                                |

In [32]:
outfile = pathlib.Path("quote.txt")
outfile

PosixPath('quote.txt')

We create some text to write (a quote from J.R. Tolkien):

In [33]:
line1 = "All that is gold does not glitter,"
line2 = "Not all those who wander are lost;"
line3 = "The old that is strong does not wither,"
line4 = "Deep roots are not reached by the frost."

#### Write the most basic way (not recommended)

The most basic way:

In [34]:
target = open(outfile, "w")

target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")
target.write(line4)
target.write("\n")

target.close()

In [35]:
type(target)

_io.TextIOWrapper

In [36]:
print(outfile.read_text())

All that is gold does not glitter,
Not all those who wander are lost;
The old that is strong does not wither,
Deep roots are not reached by the frost.

#### Write in a `with` block

Again, we can use `with` to simplify things (avoid having to `close()` the file).

In [37]:
with open(outfile, "w") as target:
    target.write(line1)
    target.write("\n")
    target.write(line2)
    target.write("\n")
    target.write(line3)
    target.write("\n")
    target.write(line4)
    target.write("\n")

You can also use writelines to provide all write elements as an iterable:

In [38]:
with open(outfile, "w") as target:
    target.writelines([line1, "\n", line2, "\n", line3, "\n", line4, "\n"])

In [39]:
print(outfile.read_text())

All that is gold does not glitter,
Not all those who wander are lost;
The old that is strong does not wither,
Deep roots are not reached by the frost.

#### Write with Pandas to comma-separated values or tab-separated values

The dataframe `df` contains the woodchuck text from above.

In [40]:
df

                                  0
0                     How much wood
1           Would a woodchuck chuck
2  If a woodchuck could chuck wood?

In [41]:
df.to_csv("woodchuck_pandas.csv")

In [42]:
df.to_csv("woodchuck_pandas.tsv", sep="\t")

#### pathlib

As previously noted, pathlib helps us write files quickly with `write_text()`, whenever flow control is not required:

In [43]:
outfile_text = "\n".join([line1, line2, line3, line4])
outfile_text

'All that is gold does not glitter,\nNot all those who wander are lost;\nThe old that is strong does not wither,\nDeep roots are not reached by the frost.'

In [44]:
outfile.write_text(outfile_text);

We are able to check if the file was written properly, and if the content is correct:

In [45]:
outfile.is_file()

True

In [46]:
print(outfile.read_text())

All that is gold does not glitter,
Not all those who wander are lost;
The old that is strong does not wither,
Deep roots are not reached by the frost.

We also have shortcuts for **deleting** the file (not supported by `open()`):

In [47]:
outfile.unlink()

In [48]:
outfile.is_file()

False

One other advantage of pathlib is using methods directly on the selected path. For example, we are able to list the contents for the directory as a list with `iterdir()`.

In [49]:
list(outfile.parent.iterdir())

[PosixPath('lesson10.ipynb'),
 PosixPath('lesson09.ipynb'),
 PosixPath('woodchuck_pandas.csv'),
 PosixPath('lesson12.ipynb'),
 PosixPath('.DS_Store'),
 PosixPath('.pytest_cache'),
 PosixPath('lesson14.ipynb'),
 PosixPath('fibo.py'),
 PosixPath('lesson13.ipynb'),
 PosixPath('lesson11.ipynb'),
 PosixPath('lesson08.ipynb'),
 PosixPath('__pycache__'),
 PosixPath('lesson02.ipynb'),
 PosixPath('lesson04.ipynb'),
 PosixPath('lesson06.ipynb'),
 PosixPath('.ipynb_checkpoints'),
 PosixPath('lesson01.ipynb'),
 PosixPath('lesson03.ipynb'),
 PosixPath('lesson07.ipynb'),
 PosixPath('lesson05.ipynb'),
 PosixPath('woodchuck_pandas.tsv')]

We can then use this to cleanup the CSV and TSV files created by our pandas export:

In [50]:
for file in outfile.parent.iterdir():
    if file.suffix in (".csv", ".tsv"):
        print(f"Removing file {file}")
        file.unlink()

Removing file woodchuck_pandas.csv
Removing file woodchuck_pandas.tsv

### Functions

Functions allow you to carry out the same task multiple times. This reduces the amount of code you write, reduces mistakes, and makes your code easier to read.

The canonical way of defining a function is as follows:

```python
def function_name(arg1: int, arg2: int) -> int:
    """
    Documentation for the function. This can be a multiline string.

    This function adds two numbers together.
    """
    return arg1 + arg2

```

Python uses the so called `snake_case` to define all variables and functions. This means that the variables are all lower case and separated by underscores.

In [51]:
def add(arg1: int, arg2: int) -> int:
    """
    Documentation for the function. This can be a multiline string.

    This function adds two numbers together.
    """
    return arg1 + arg2

In [52]:
add(1, 2)

3

#### Typing

You may also have noticed the hints `: int` and `-> int` after the argument names. These are called type hints, and they serve as advice for readers on how to best use the function (what it _expects_, what it _returns_). It is considered a good practice to type your code. We will see later in the course how to check those against your code base to ensure consistency. By default, typing does nothing more than add context.

As an example, despite the function being typed, the following examples all work.

In [53]:
?add

Signature: add(arg1: int, arg2: int) -> int
Docstring:
Documentation for the function. This can be a multiline string.

This function adds two numbers together.
File:      /var/folders/wf/l1cgt65d4yj59p5x0xd9t7500000gn/T/ipykernel_97889/668547693.py
Type:      function

In [54]:
add(10, 5)

15

In [55]:
add(1.3, 4.4)

5.7

In [56]:
add("AAA", "bbb")

'AAAbbb'

In [57]:
add(["A"], ["B"])

['A', 'B']

#### Printing

If you need some feedback of what is happening inside the function, you can use `print` statements. They have no influence on function output, and can be used for debugging values or observing function behaviour.

In [58]:
def say_hello():
    print("Hello, world!")

In [59]:
say_hello()
say_hello()
say_hello()

Hello, world!
Hello, world!
Hello, world!

In [60]:
def print_a_string(foo: str) -> None:
    print(foo)

In [61]:
print_a_string("Here is a string.")

Here is a string.

In [62]:
x = "A string saved as a variable."
print_a_string(x)

A string saved as a variable.

In [63]:
y = 300
print_a_string(y)

300

In [64]:
def print_two_things(one, two):
    print(f"{one} AND {two}")

In [65]:
x = "yes"
y = 10
print_two_things(x, y)

yes AND 10

#### Variable number of arguments

The following would not work when trying to sum more than two elements, because **the original function expects two elements**:

```python
add(1, 2, 3, 4, 5, 6)
```

# try it!
add(1, 2, 3, 4, 5, 6)

The solution is to unpack the elements using the **asterisk (*)** operator.

In [66]:
def variable_elements_add(*elements: int) -> int:
    total_sum = 0
    for element in elements:
        total_sum = total_sum + element
    return total_sum

In [67]:
variable_elements_add(1, 2, 3, 4, 5, 6)

21

You can use the asterisk to also unpack a tuple into the call arguments:

In [68]:
elements = (1, 2, 3, 4, 5, 6)
elements

(1, 2, 3, 4, 5, 6)

In [69]:
variable_elements_add(*elements)

21

Here is our example with printing many things, this time with variable arguments:

In [70]:
def print_many_things(*blob):
    things = [str(b) for b in blob]
    print(", ".join(things))

In [71]:
print_many_things(1, "2", "3", "4", ["x", "y", "z"])

1, 2, 3, 4, ['x', 'y', 'z']

#### Named arguments

Function named arguments can reference how the arguments were named in the function definitions.

Here, when calling functions using the argument names, the order doesn't really matter.

In [72]:
?print_two_things

Signature: print_two_things(one, two)
Docstring: <no docstring>
File:      /var/folders/wf/l1cgt65d4yj59p5x0xd9t7500000gn/T/ipykernel_97889/3220160644.py
Type:      function

In [73]:
print_two_things(two="second", one="first")

first AND second

In [74]:
def multiply(x: int, multiplier: int) -> int:
    return x * multiplier

In [75]:
multiply(5, 3)

15

In [76]:
multiply(5, multiplier=3)

15

#### Default arguments

Arguments can be defined default values, which are picked whenever the function call is not provided.

In [77]:
def format_price(amount: float, decimals: int = 2, currency: str = "€") -> str:
    """Formats the price to the decimals and currency expected."""
    return f"{currency} {amount:.{decimals}f}"

In [78]:
format_price(4.5)

'€ 4.50'

In [79]:
format_price(4.5, currency="$")

'$ 4.50'

In [80]:
format_price(4.5678, decimals=8, currency="₿")

'₿ 4.56780000'

#### Returning

A function will output whatever is inside your return statement. If the function does not have a return statement it will return `None`.

In [81]:
def return_sum(a: int, b: int) -> int:
    return a + b

In [82]:
return_sum(5, 8)

13

You can store those return values and work with them further:

In [83]:
x = return_sum(8, 13)
x

21

In [84]:
x * 2

42

Here is an example where instead of printing the result, we instead return it as a formatted string:

In [85]:
def combine_with_commas(*blob):
    blob_as_string = [str(b) for b in blob]
    return ",".join(blob_as_string)

In [86]:
combine_with_commas(40, 50, 60)

'40,50,60'

In [87]:
combine_with_commas(40, 50, 60, 70, "hello")

'40,50,60,70,hello'

If you want to return multiple entries from a single function, you can use a tuple to organize the response.

**Note**: we often prefer to separate the concerns into specialized functions whenever possible. This makes them easier to understand.

In [88]:
def sum_product_exponent(v1: int, v2: int):
    s = v1 + v2
    p = v1 * v2
    e = v1**v2
    return s, p, e

In [89]:
sum_product_exponent(2, 5)

(7, 10, 32)

In [90]:
my_sum, my_product, my_exponent = sum_product_exponent(2, 5)

In [91]:
my_sum

7

In [92]:
my_product

10

In [93]:
my_exponent

32

#### lambdas

`lambda` functions are inline functions with a single operation. They are often used to be passed as reference to other functions

In [94]:
x = lambda a, b: a + b

In [95]:
x(1, 2)

3

Here are two examples of how to use those lambdas with a `filter()` and a `map()`:

In [96]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [97]:
even_numbers = filter(lambda x: x % 2 == 0, a)
list(even_numbers)

[2, 4, 6, 8, 10]

In [98]:
square_numbers = map(lambda x: x**2, a)
list(square_numbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]